### ISSUE TITLE
Fakeplate issue

### ISSUE THREAD

**Issue by KrnkTV** [reyyghi/rhd_garage#11]
You makw pull request for fakeplates and they working with only 1 ussue. When police trying to impound vehicle in context show original owner not fake owner when car is with fakeplate

**Comment by reyyghi** [comment]
if it is confiscated by the police it will still display the original owner's name because in qb-core it only uses a fake plate instead of a fake owner's name. if you want to display a fake owner's name when a vehicle with a fake license plate is confiscated by the police, you can edit it yourself

**Comment by KrnkTV** [comment]
With qb-policejob police impound show you fake name not original owner name for that i make this issue
