### ISSUE TITLE
rhd_notify and errors for vehicles_names

### ISSUE THREAD

**Issue by Rolyt1212** [reyyghi/rhd_garage#31]
![image](https://github.com/reyyghi/rhd_garage/assets/147928850/7ca0139d-b1ab-4e50-9e73-82699e0b5fd8)
where can i find it

**Comment by Rolyt1212** [comment]
![image](https://github.com/reyyghi/rhd_garage/assets/147928850/071fd450-e967-4b6b-880c-d6daeb7c2eae)

**Comment by reyyghi** [comment]
> ![image](https://private-user-images.githubusercontent.com/147928850/324579299-7ca0139d-b1ab-4e50-9e73-82699e0b5fd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MzcxOTAsIm5iZiI6MTcxMzkzNjg5MCwicGF0aCI6Ii8xNDc5Mjg4NTAvMzI0NTc5Mjk5LTdjYTAxMzlkLWIxYWItNGU1MC05ZTczLTgyNjk5ZTBiNWZkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQwNTM0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjBkM2MwOTAzNmMzN2RlNzQyMTYyNWFlOWQ0NWY3M2U3ZTg1ZDc4ZDkxNTNhNGFhM2RiZTlmZWViZWM2MWM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qVdxvXkZ7D_XsIken8aCfUSR_FfrWmLfyY_8YbfP-u4) where can i find it

I don't share that, use your server's notify function

**Comment by reyyghi** [comment]
> ![image](https://private-user-images.githubusercontent.com/147928850/324583364-071fd450-e967-4b6b-880c-d6daeb7c2eae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MzcxOTAsIm5iZiI6MTcxMzkzNjg5MCwicGF0aCI6Ii8xNDc5Mjg4NTAvMzI0NTgzMzY0LTA3MWZkNDUwLWU5NjctNGI2Yi04ODBjLWQ2ZGFlYjdjMmVhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQwNTM0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNDBmY2ZhOGY2NzI1MDY1ZjExNzFjNDU3ZGY5M2MzYWEwZTk1Nzc5M2RhYTJkY2U3MjY5M2FiOTlkZDRhYmIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EiiJYGy0Xw8aWm7LtbUAaP8M2tMci08ugd0XMd0HEeg)

backup your player_vehicles database, and run the sql that I have provided

**Comment by Rolyt1212** [comment]
i do that but same error

**Comment by Rolyt1212** [comment]
![image](https://github.com/reyyghi/rhd_garage/assets/147928850/c0034357-756c-45df-9178-dcfef8381b2b)

**Comment by Rolyt1212** [comment]
Install everything new

**Comment by reyyghi** [comment]
> ![image](https://private-user-images.githubusercontent.com/147928850/325319530-c0034357-756c-45df-9178-dcfef8381b2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNjc4ODcsIm5iZiI6MTcxNDE2NzU4NywicGF0aCI6Ii8xNDc5Mjg4NTAvMzI1MzE5NTMwLWMwMDM0MzU3LTc1NmMtNDVkZi05MTc4LWRjZmVmODM4MWIyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNlQyMTM5NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYWI2YmE0OTgzYzBiMGNiYzI5YWJiOTllYWNlMGY5OWUzNzQ4MTM1Y2IwNGFmNzk4NGUzMDE1ZDg2ZmVhNjRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._irBU7Q1d_-tsKGtlbXMmz_C5eW1XyZM02DMWt4rIXY)

change the collation of the citizenid column in the players table to utf8mb4_unicode_ci
