### ISSUE TITLE
When buying a car on dealer it wont store it on the garage

### ISSUE THREAD

**Issue by SpectrumRaijin** [reyyghi/rhd_garage#32]
When trying to store the vehicle it tells me that I dont own that car.

Thats the error I get.  

But when i go to the impound I can retrieve it but not store on the garage.

![image](https://github.com/reyyghi/rhd_garage/assets/83751111/9f71614c-6ccf-441c-8e6d-938cc445ba23)

![imagen_2024-04-30_110842237](https://github.com/reyyghi/rhd_garage/assets/83751111/08a7d940-72f8-45ca-8c56-c8d0ad6d00ec)

If I use an older version of the script, I can store normally my car

**Comment by reyyghi** [comment]
> When trying to store the vehicle it tells me that I dont own that car.
> 
> Thats the error I get.
> 
> But when i go to the impound I can retrieve it but not store on the garage.
> 
> ![image](https://private-user-images.githubusercontent.com/83751111/326913602-9f71614c-6ccf-441c-8e6d-938cc445ba23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NTk0NDIsIm5iZiI6MTcxNDU1OTE0MiwicGF0aCI6Ii84Mzc1MTExMS8zMjY5MTM2MDItOWY3MTYxNGMtNmNjZi00NDFjLThlNmQtOTM4Y2M0NDViYTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDEwMjU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiMjdhN2ZiYWYyMTRkNTNmMWEyZjczNmM3MjQ5MjFiYjRkYjllNGE2MWJkOTNlMzlhNDgyMzk2N2EyZWRhNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y1N2PukGLHQzQWqK9QY0DLb11ReGUSKQSRqyxGxtwxE)
> 
> ![imagen_2024-04-30_110842237](https://private-user-images.githubusercontent.com/83751111/326913080-08a7d940-72f8-45ca-8c56-c8d0ad6d00ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NTk0NDIsIm5iZiI6MTcxNDU1OTE0MiwicGF0aCI6Ii84Mzc1MTExMS8zMjY5MTMwODAtMDhhN2Q5NDAtNzJmOC00NWNhLThjNTYtYzhkMGFkNmQwMGVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDEwMjU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4Yzk4MjEwZTViNjhiNDViYjkyMjkzNTJlZmM5ZTc3MDczOTA4MWQwZmVmYWEyYjQxYWJlMWE4MmIwNmU1M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eCE3M4FuF5j-6y1JjMy4oVdf_zcGzmnv5NFZWtlxPro)
> 
> If I use an older version of the script, I can store normally my car

change the collation of the citizenid column in the players table to utf8mb4_unicode_ci

**Comment by duddi0** [comment]
I changed the 'citizenid' column in the players table to utf8mb4_unicode_ci, but encountered the same error.

![Screenshot 2024-05-03 102118](https://github.com/reyyghi/rhd_garage/assets/143247737/b42ac95b-b7ae-4598-8193-470b932a3251)

This is the changed one.

![Screenshot 2024-05-03 103444](https://github.com/reyyghi/rhd_garage/assets/143247737/1b3043b1-845d-47fd-a6bb-6263699d4ea7)
