### ISSUE TITLE
Encountering Error: Changing 'citizenid' Column in Players Table

### ISSUE THREAD

**Issue by duddi0** [reyyghi/rhd_garage#33]
I changed the 'citizenid' column in the players table to utf8mb4_unicode_ci, but encountered the same error.

![Screenshot 2024-05-03 102118](https://github.com/reyyghi/rhd_garage/assets/143247737/b42ac95b-b7ae-4598-8193-470b932a3251)

This is the changed one.

![Screenshot 2024-05-03 103444](https://github.com/reyyghi/rhd_garage/assets/143247737/1b3043b1-845d-47fd-a6bb-6263699d4ea7)

**Comment by SpectrumRaijin** [comment]
for esx it works. I dont remember why  but my identifier column didnt have the  collation.

**Comment by duddi0** [comment]
> for esx it works. I dont remember why but my identifier column didnt have the collation.

But I am unable to remove the collision in the 'citizenid' column in the Players table.
