### ISSUE TITLE
2 errors

### ISSUE THREAD

**Issue by KrnkTV** [reyyghi/rhd_garage#7]
if i setup garage in config like this
job = {['police'] = 1, ['bcso'] = 1, ['pbso'] = 1, ['sast'] = 1, ['sasp'] = 1, ['sapr'] = 1, ['sahp'] = 1}, i receive this error and garage is not pop up
![Screenshot_22](https://github.com/reyyghi/rhd_garage/assets/82491495/4d9863b8-2420-4368-9f6b-746d4a67ba05)
For some reason he spam all the time this error
![Screenshot_21](https://github.com/reyyghi/rhd_garage/assets/82491495/2736c780-8d41-4046-8527-20a5826bdc40)

**Comment by reyyghi** [comment]
for line 86: did you enter job name or job type name? because I haven't added checking for job types, like (leo, etc.). I suggest you use the job name temporarily.

for line 189: have you used the latest version of qb-houses?

**Comment by KrnkTV** [comment]
i enter multiply job names
job = {['police'] = 1, ['bcso'] = 1, ['pbso'] = 1, ['sast'] = 1, ['sasp'] = 1, ['sapr'] = 1, ['sahp'] = 1},

And i use latest version of qb-houses

I realize one more issue. Your garage its not server side spawn because when you move away from car she despawn

**Comment by KrnkTV** [comment]
everything else is more than perfect garages working very well
