### ISSUE TITLE
Phone information

### ISSUE THREAD

**Issue by KrnkTV** [reyyghi/rhd_garage#8]
First i want to thank you for fixing other stuff which i report you now garages working without issue. Only issue which i found is when i open garage app in phone garage name is undefined and cant take right information for fuel body and body damage. I use Renewed-Phone.

**Comment by KrnkTV** [comment]
i think have issue with exports.rhd_garage:getDataVehicle() he didn't take right information

**Comment by reyyghi** [comment]
if you are using renewed phone, you have to change in client/garage.lua and server/garage.lua, don't use exports from rhd_garage because it doesn't work for renewed phones

**Comment by KrnkTV** [comment]
Okay can you help me to make it to work?

**Comment by reyyghi** [comment]
I will make rhd_garage work with Renewed-Phone in the next update
